# Generated by Django 4.1.7 on 2023-04-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='last_name',
            new_name='familiya',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='first_name',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='phone',
            new_name='telefon_raqam',
        ),
    ]
