# Generated by Django 4.2 on 2023-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.PositiveIntegerField(default=1)),
                ('awards', models.PositiveIntegerField(default=1)),
                ('customer', models.PositiveIntegerField(default=1)),
                ('stuff', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
