# Generated by Django 4.2 on 2023-05-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_pizzanumbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzanumbers',
            options={'verbose_name': 'Pizza numbers', 'verbose_name_plural': 'Pizza numbers'},
        ),
    ]
